// Dictionaries and keyword collections used across the form automation flow.
// Extracted from the previous legacyDomFill implementation to centralise shared constants.

export const FIELD_KEYWORDS: Record<string, string[]> = {
  company: ['社名', '企業名', '法人名', '個人', '組織', '所属', '団体', '勤務先', 'company', 'Company', 'COMPANY', 'corporate', 'Corporate'],
  department: ['部署', '部門'],
  industry: ['業種'],
  position: ['役職'],
  subject: ['件名', 'タイトル', '題名', 'Subject', 'subject'],
  member: ['従業員数', '社員数'],
  sei: ['姓', '苗字'],
  seiKana: ['セイ'],
  meiKana: ['メイ'],
  seiHira: ['せい'],
  meiHira: ['めい'],
  name: ['名前', '氏名', '担当者', 'なまえ', 'Name', 'name'],
  furigana: ['フリガナ'],
  hiragana: ['ふりがな'],
  email: ['メール', 'MAIL', 'Mail', 'mail', '確認', '@'],
  tel: ['TEL', 'Tel', 'tel', '電話', '携帯', '直通', '連絡先'],
  fax: ['FAX', 'Fax', 'fax', 'ファックス'],
  zip: ['郵便', '〒'],
  pref: ['都道府県'],
  city: ['市区町村'],
  address: ['番地'],
  building: ['ビル', '建物'],
  fullAddress: ['住所', '所在地', 'ところ', 'ADDRESS', 'Address', 'address'],
  url: ['URL', 'WEB', 'Web', 'web', 'ホームページ', 'ウェブサイト', 'http', 'リンク'],
};

export const SUBMIT_KEYWORDS = {
  text: [
    '送信',
    '送 信',
    '送　信',
    'この内容で送信',
    '確認',
    '確 認',
    '確　認',
    'Send',
    'SEND',
    'Submit',
    'SUBMIT',
    '次へ',
    '次に進む',
    'はい',
    'OK',
    '同意する',
    '続行',
  ],
  value: [
    '送信',
    '送 信',
    '送　信',
    'この内容で送信',
    '確認',
    '確 認',
    '確　認',
    'Send',
    'SEND',
    'Submit',
    'SUBMIT',
    '問い合',
    '問合',
    '次へ',
    '次に進む',
    'はい',
    'OK',
    '同意する',
    '続行',
  ],
  alt: [
    '送信',
    '確認',
    'Send',
    'SEND',
    'Submit',
    'SUBMIT',
    '問い合',
    '問合',
    '次へ',
    '次に進む',
    'はい',
    'OK',
    '同意する',
    '続行',
  ],
} as const;

export const EXCLUDE_SUBMIT_KEYWORDS = [
  '検索',
  'Search',
  'さがす',
  '探す',
  '絞り',
  'filter',
  '戻る',
  'キャンセル',
  '取消',
  'リセット',
  'clear',
  'クリア',
  'プレビュー',
] as const;

// Set of keywords that usually signal confirmation/consent checkboxes.
export const AGREE_KEYWORDS = ['同意', '承諾', '利用規約', 'プライバシー', '個人情報'];

